export enum PERMISSIONS {
    ADMIN_VIEW = 'monitorHasAdminView',
    OPERATIONS_VIEW = 'monitorHasOperationsView',
    UTILITY_BILL_DETAILS_VIEW = 'monitorHasUtilityBillDetailsView',
    LABS_VIEW = 'monitorHasLabsView',
    SPECIAL_PROGRAMS_VIEW = 'monitorHasSpecialProgramsView',
    CREATE_SUBSCRIPTIONS = 'monitorCanCreateSubscriptions',
    EDIT_SUBSCRIPTIONS = 'monitorCanEditSubscriptions',
    DELETE_SUBSCRIPTIONS = 'monitorCanDeleteSubscriptions',
    CREATE_OVERRIDES = 'monitorCanCreateOverrides',
    DELETE_OVERRIDES = 'monitorCanDeleteOverrides',
    UPDATE_BILLING = 'monitorCanUpdateBilling',
    ACUMEN_API = 'monitorCanUseAcumenApi',
    MANAGE_SPECIAL_PROGRAMS = 'monitorCanManageSpecialPrograms',
    CREATE_UPDATE_SITES = 'monitorCanSyncSites',
    EDIT_DEVICE_CONFIG_PV = 'monitorCanEditPvConfig',
    EDIT_COMPANY_PROFILE = 'canEditCompanyProfile',
    EDIT_COMPANY_USERS = 'canEditCompanyUsers',
    EDIT_COMPANY_SUBSCRIPTION = 'canEditCompanySubscriptionSettings',
    ETB_ADMIN_EDIT_ADMIN_ROLES = 'etbAdminCanEditEtbAdminRoles',
    ETB_ADMIN_EDIT_COMPANIES = 'etbAdminCanEditCompanies',
    INVITE_USERS = 'canInviteUsers',
    EDIT_DATA_SOURCES = 'monitorCanEditDataSources',
    MONITOR_OVERRIDE_VIEW = 'monitorHasOverrideView',
}